version: '2.4'

services:

  ubuntu18-systemd-full:
    container_name: ubuntu
    hostname: ubuntu
    image: adiprint/ubuntu18-systemd-full:latest
    privileged: true
    stdin_open: false
    tty: false
    restart: "no"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    network_mode: bridge
